###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:16.15.0 As development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

# COPY --chown=node:node .env ./

RUN npm ci

COPY --chown=node:node . .

USER node

###################
# BUILD FOR PRODUCTION
###################

FROM node:16.15.0 As build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

# COPY --chown=node:node .env ./

COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

COPY --chown=node:node . .

RUN npm run build

ENV NODE_ENV prod

RUN npm ci --only=production && npm cache clean --force

USER node

###################
# PRODUCTION
###################

FROM node:16.15.0 As production

COPY --chown=node:node --from=build /usr/src/app ./

CMD [ "npm", "run", "start" ]
